[package]
name = "cdc-source-pg-common"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
tokio = { version = "1", features = ["rt"] }
tokio-postgres = { version = "0.7" }
thiserror = "2"
tokio-postgres-rustls = "0.13"
tracing = "0.1"
webpki-roots = "0.26"
